### ISSUE TITLE
Txt token Header 

### ISSUE THREAD

**Issue by naveencm4u1** [oauth-wg/oauth-transaction-tokens#21] opened 2023-07-12 20:48 UTC
I assume the token is sent in the header. Do we have any recommendations for the header name?

**Comment by gffletch** [comment] 2023-09-05 18:56
In what situations would we have multiple tokens such that leveraging the Authorization header is not sufficient? My preference would be to leverage the Authorization header. Receiving entities can distinguish token types based on the JWT Header.

**Comment by naveencm4u1** [comment] 2023-09-05 20:35
@gffletch It is mainly in the transition phase. In our case, we want to pass both Access Token and Transaction Token until all the downstream are ready.

**Comment by gffletch** [comment] 2023-10-31 11:11
This topic has come up again so re-opening the issue as it's something I think we need to address in the specification.

**Comment by tulshi** [comment] 2023-11-14 00:12
Duplicate of #49

**Comment by obfuscoder** [comment] 2024-01-30 11:54
I believe, this issue can be closed as well?

**Closed** 2024-02-01 22:48 UTC
